# Generated by Django 6.0.3 on 2026-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('EMPRESTADO', 'Emprestado')], default='DISPONIVEL', max_length=20),
        ),
    ]
