# Generated by Django 6.0.3 on 2026-05-09 23:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acervo', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80, verbose_name='Ação')),
                ('entidade', models.CharField(max_length=80, verbose_name='Entidade')),
                ('registro_id', models.PositiveIntegerField(verbose_name='ID do registro')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data do empréstimo')),
                ('data_prevista_devolucao', models.DateField(verbose_name='Data prevista de devolução')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de devolução')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], db_index=True, default='ATIVO', max_length=12, verbose_name='Situação')),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='acervo.exemplar', verbose_name='Exemplar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10, verbose_name='Situação do pagamento')),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='circulacao.emprestimo', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True, verbose_name='Data da reserva')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de expiração')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], db_index=True, default='ATIVA', max_length=12, verbose_name='Situação')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='catalogo.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_reserva'],
            },
        ),
        migrations.AddConstraint(
            model_name='emprestimo',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ATIVO')), fields=('exemplar',), name='unique_emprestimo_ativo_por_exemplar'),
        ),
    ]
