# Generated by Django 6.0.3 on 2026-05-13 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_reservas(apps, schema_editor):
    Reserva = apps.get_model('circulacao', 'Reserva')

    reservas_ativas = Reserva.objects.filter(status='ATIVA').order_by('data_reserva', 'id')
    chaves_vistas = set()
    for reserva in reservas_ativas:
        chave = (reserva.livro_id, reserva.usuario_id)
        if chave in chaves_vistas:
            reserva.status = 'CANCELADA'
            reserva.save(update_fields=['status'])
            continue
        chaves_vistas.add(chave)

    for reserva in Reserva.objects.filter(protocolo__isnull=True):
        reserva.protocolo = f'RSV-{reserva.pk:06d}'
        reserva.save(update_fields=['protocolo'])


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_alter_exemplar_status'),
        ('catalogo', '0003_capalivro'),
        ('circulacao', '0002_remove_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_emprestimo'], 'verbose_name': 'Emprestimo', 'verbose_name_plural': 'Emprestimos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['data_reserva', 'id'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='exemplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='acervo.exemplar', verbose_name='Exemplar separado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='protocolo',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('FILA', 'Fila de espera'), ('RETIRADA', 'Retirada no balcao')], db_index=True, default='FILA', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de devolucao'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True, verbose_name='Data do emprestimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(verbose_name='Data prevista de devolucao'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], db_index=True, default='ATIVO', max_length=12, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='emprestimo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='circulacao.emprestimo', verbose_name='Emprestimo'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10, verbose_name='Situacao do pagamento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de expiracao'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], db_index=True, default='ATIVA', max_length=12, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.RunPython(backfill_reservas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ATIVA')), fields=('livro', 'usuario'), name='unique_reserva_ativa_por_livro_usuario'),
        ),
    ]
