# Generated by Django 6.0.3 on 2026-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
