# Generated by Django 6.0.3 on 2026-05-13 00:00

import apps.catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_livro_isbn_livro_isbn_10_livro_isbn_13'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=apps.catalogo.models.capa_livro_upload_to)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capa', to='catalogo.livro')),
            ],
            options={
                'verbose_name': 'capa de livro',
                'verbose_name_plural': 'capas de livros',
            },
        ),
    ]
